[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
  headers = {Cache-Control = "no-cache, no-store, must-revalidate"}

[[redirects]]
  from = "/qr-generator.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = true

# Headers adicionales para evitar caché
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff" 